<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\flexilayout_builder\Entity\FlexibleLayoutBuilderEntityViewDisplay;
use Drupal\flexilayout_builder\Plugin\SectionStorage\DefaultsSectionStorage;
use Drupal\flexilayout_builder\Plugin\SectionStorage\OverridesSectionStorage;

/**
 * Implements hook_entity_type_alter().
 */
function flexilayout_builder_entity_type_alter(array &$entity_types) {
  $entity_types['entity_view_display']
    ->setClass(FlexibleLayoutBuilderEntityViewDisplay::class);
}

/**
 * Implemens hook_layout_builder_section_storage().
 */
function flexilayout_builder_layout_builder_section_storage_alter(&$definitions) {
  $definitions['defaults']->setClass(DefaultsSectionStorage::class);
  $definitions['overrides']->setClass(OverridesSectionStorage::class);
}

/**
 * Implements hook_builder_module_implements_alter().
 */
function flexilayout_builder_module_implements_alter(&$implementations, $hook) {
  if ($hook === 'entity_type_alter') {
    // Ensure that this module's implementation of hook_entity_type_alter() runs
    // last so that our entity class is used for entity_view_Display entities.
    $group = $implementations['flexilayout_builder'];
    unset($implementations['flexilayout_builder']);
    $implementations['flexilayout_builder'] = $group;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function flexilayout_builder_form_layout_builder_add_block_alter(array &$form, FormStateInterface $form_state) {
  /** @var \Drupal\layout_builder\SectionStorageInterface $section_storage */
  list($section_storage, $delta, $region, $plugin_id) = $form_state->getBuildInfo()['args'];
  $form_state->set('section_storage', $section_storage);

  _flexilayout_builder_layout_builder_block_form_alter($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function flexilayout_builder_form_layout_builder_update_block_alter(array &$form, FormStateInterface $form_state) {
  /** @var \Drupal\layout_builder\SectionStorageInterface $section_storage */
  list($section_storage, $delta, $region, $uuid) = $form_state->getBuildInfo()['args'];
  $form_state->set('section_storage', $section_storage);
  $form_state->set('component', $section_storage->getSection($delta)->getComponent($uuid));

  _flexilayout_builder_layout_builder_block_form_alter($form, $form_state);
}

/**
 * Add magical extra things to the block form.
 */
function _flexilayout_builder_layout_builder_block_form_alter(array &$form, FormStateInterface $form_state) {
  $form['flexilayout_builder'] = [
    '#type' => 'container',
  ];

  $class = $form_state->get('component') ? $form_state->get('component')->get('class') : '';
  $form['flexilayout_builder']['class'] = [
    '#type' => 'textfield',
    '#title' => t('Block Classes'),
    '#default_value' => $class,
  ];

  $form['#submit'][] = '_flexilayout_builder_layout_builder_block_form_submit';
}

/**
 * Submit.
 */
function _flexilayout_builder_layout_builder_block_form_submit() {

}
