services:
  plugin.manager.exec_environment_component:
    class: Drupal\exec_environment\EnvironmentComponentManager
    arguments: ['@container.namespaces', '@cache.discovery_noenv', '@module_handler']
  plugin.manager.exec_environment_impact_applicator:
    class: Drupal\exec_environment\EnvironmentImpactApplicatorManager
    arguments: [ '@container.namespaces', '@cache.discovery_noenv', '@module_handler' ]
  environment_stack:
    class: Drupal\exec_environment\EnvironmentStack
    arguments: ['@event_dispatcher']
    calls:
      - [setContainer, ['@service_container']]
    tags:
      - { name: persist }
  exec_environment.authentication_subscriber:
    class: Drupal\exec_environment\EventSubscriber\AuthenticationSubscriber
    arguments: [ '@authentication', '@environment_stack' ]
    tags:
      - { name: event_subscriber }
  exec_environment.detect_default_environment_subscriber:
    class: Drupal\exec_environment\EventSubscriber\DetectDefaultEnvironmentSubscriber
    arguments: [ '@plugin.manager.exec_environment_component', '@current_user' ]
    tags:
      - { name: event_subscriber }
  exec_environment.config_import_export_subscriber:
    class: Drupal\exec_environment\EventSubscriber\ConfigImportExportSubscriber
    arguments: [ '@config.factory', '@config.storage' ]
    tags:
      - { name: event_subscriber }
  exec_environment.set_current_user_permissions:
    class: Drupal\exec_environment\ExecEnvironmentSetCurrentUserPermissions
    arguments: [ '@entity_type.manager' ]
  cache.discovery_noenv:
    class: Drupal\Core\Cache\CacheBackendInterface
    tags:
      - { name: cache.bin, default_backend: cache.backend.chainedfast }
    factory: cache_factory:get
    arguments: [ discovery_noenv ]

