<?php

use Drupal\Core\Entity\ContentEntityForm;

/**
 * Implements hook_entity_type_build()
 *
 * @param \Drupal\Core\Entity\EntityTypeInterface[] $entity_types
 */
function rlmcrm_entity_type_build(&$entity_types) {
  if ($entity_type = $entity_types['user']) {
    $entity_type->setFormClass('add_individual', ContentEntityForm::class);
    $entity_type->setFormClass('add_organisation', ContentEntityForm::class);
    $entity_type->setFormClass('edit_individual', ContentEntityForm::class);
    $entity_type->setFormClass('edit_organisation', ContentEntityForm::class);
  }
}
