<?php

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\entity\BundleFieldDefinition;

/**
 * Implements hook_entity_base_field_info().
 */
function task_checklist_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  if ($entity_type->id() == 'task') {
    // Use bundle field definition to avoid this going on the main task table.
    $fields['checklist'] = BundleFieldDefinition::create('checklist')
      ->setLabel(new TranslatableMarkup('Checklist'))
      ->setDisplayConfigurable('view', TRUE);
  }

  return $fields;
}
